#
# Punishments Plus 1.0-RELEASE
#
# By LoryTheRock24
#
Settings:
  #
  # This option define if the server can say to all the players a message for when a player will banned
  # from the server.
  #
  enablePublicBanMessage: true
  #
  # This option define if the server can say to all the players a message for when a player will unbanned
  # from the server.
  #
  enablePublicUnbanMessage: true
  #
  # This option define if the server can say to all the players a message for when a player will kicked
  # from the server.
  #
  enablePublicKickMessage: true
  #
  # This option define if the server can say to all the players a message for when a player will muted
  # from the server.
  #
  enablePublicMuteMessage: true
  #
  # This option define if the server can say to all the players a message for when a player will unmuted
  # from the server.
  #
  enablePublicUnmuteMessage: true
  #
  # The ban override players
  #
  overridePlayers:
    - aPlayer
    - AnotherPlayer
  #
  # This is the list of the prohibited commands for a muted player.
  #
  prohibitedCommandsOnMute:
    - /msg
    - /tell
    - /me
    - /minecraft:me
  #
  # The messages.
  #
  Messages:
    #
    # This is the message that will be displayed on the loading screen of a player that has
    # been permanently banned from the server
    #
    joinBanPermanently: "&c&lYOU ARE PERMANENTLY BANNED FROM THIS SERVER!\n &cBanned by:&f %BAN-EXECUTOR% \n &cMotivation:&f %MOTIVATION%"
    #
    # The public ban message.
    #
    publicBanMessage: "&c[PunishmentsPlus]&f %BANNED-PLAYER%&c was banned from the server by&f %BAN-EXECUTOR%&c for&f %MOTIVATION%.\n&cDuration:&f %DURATION%."
    #
    # This is the message that will be displayed on the screen of a player when he was kicked from the server.
    #
    kickMessage: "&c&lYOU ARE KICKED FROM THIS SERVER!\n &cKicked by:&f %KICK-EXECUTOR% \n &cMotivation:&f %MOTIVATION%"
    #
    # The public kick message.
    #
    publicKickMessage: "&c[PunishmentsPlus]&f %KICKED-PLAYER%&c was kicked from the server by&f %KICK-EXECUTOR%&c for&f %MOTIVATION%."
    #
    # The public unban message.
    #
    publicUnbanMessage: "&a[PunishmentsPlus] %BANNED-PLAYER% was unbanned from the server by %UNBAN-EXECUTOR%."
    #
    # The message for when a player execute a command, but he hasn't got the permission.
    #
    noPermission: "&c[PunishmentsPlus]&f You don't have the necessary permission to do that."
    #
    # The message for when a player execute a command, but the command's syntax is incorrect.
    #
    syntaxError: "&c[PunishmentsPlus]&f Command syntax incorrect! use /pphelp for the plugin commands' list."
    #
    # The message for when a player try to ban an already banned player.
    #
    alreadyBanned: "&c[PunishmentsPlus]&f That player was already banned."
    #
    # The message for when a player ban another player for permanently
    #
    banSuccessful: "&c[PunishmentsPlus]&f You have permanently banned %BANNED-PLAYER% for %MOTIVATION%"
    #
    # The message for when a player try to ban a player into the overrides players' list
    #
    banImpossible: "&c[PunishmentsPlus]&f You can't ban that player."
    #
    # The message for when a player try to unban a player but he isn't banned
    #
    notBanned: "&c[PunishmentsPlus]&f That player isn't banned."
    #
    # The message for when a player unban a player.
    #
    playerUnbanned: "&c[PunishmentsPlus]&f You have unbanned %BANNED-PLAYER%"
    #
    # The message for when a player try to kick a player into the overrides players' list
    #
    kickImpossible: "&c[PunishmentsPlus]&f You can't kick that player."
    #
    # The message for when a player ban another player for permanently
    #
    kickSuccessful: "&c[PunishmentsPlus]&f You have kicked %KICKED-PLAYER% for %MOTIVATION%"
    #
    # Message for when a player try to kick an offline player.
    #
    kickPlayerNotOnline: "&c[PunishmentsPlus]&f You can't kick an offline player."
    #
    # Message for when a muted player write a message in chat
    #
    mutedPlayerMessage: "&cYou are muted from the chat!"
    #
    # This message was send to a player when hi will be muted.
    #
    privateMuteMessage: "&c[PunishmentsPlus]&c You've been muted from the server by&f %MUTE-EXECUTOR%&c for&f %MOTIVATION%"
    #
    # The public mute message.
    #
    publicMuteMessage: "&c[PunishmentsPlus]&f %MUTE-EXECUTOR%&c has muted&f %MUTED-PLAYER%&c for&f %MOTIVATION%"
    #
    # This message was send to a player when hi will be unmuted.
    #
    privateUnmuteMessage: "&c[PunishmentsPlus]&c You've been unmuted from the server by&f %MUTE-EXECUTOR%"
    #
    # The public unmute message.
    #
    publicUnmuteMessage: "&a[PunishmentsPlus] %MUTE-EXECUTOR% has unmuted %MUTED-PLAYER%"
    #
    # The message for when a player try to mute a player into the overrides players' list
    #
    muteImpossible: "&c[PunishmentsPlus]&f You can't mute that player."
    #
    # The message for when a player try to ban an already banned player.
    #
    alreadyMuted: "&c[PunishmentsPlus]&f That player was already muted."
    #
    # The message for when a player mute a player from the server chat.
    #
    muteSuccessful: "&c[PunishmentsPlus]&c You've muted&f %MUTED-PLAYER%&c for&f %MOTIVATION%"
    #
    # The message for when a player try to unmute a player but he isn't muted
    #
    notMuted: "&c[PunishmentsPlus]&f That player isn't muted."
    #
    # The message for when a player unmute a muted player.
    #
    unmuteSuccessful: "&c[PunishmentsPlus]&f You have unmuted %MUTED-PLAYER%"