name: PunishmentsPlus
version: 1.0.1
main: ro.plugin.punishmentsplus.PunishmentsPlus
authors: [LoryTheRock24]
description: Very good plugin for applicate a ban / warn / kick to a player.
commands:
  ban:
    description: Ban a player from the server.
  unban:
    description: Unban a player from the server.
  kick:
    description: Kick a player from the server.
  pphelp:
    description: View the plugin's help page.
  mute:
    description: Mute a player from the server's chat.
  unmute:
    description: Unmute a muted player from the server's chat.